spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.0.13:3306/getsoaked?useSSL=false
#    url: jdbc:mysql://localhost:3306/getsoaked?useSSL=false
    username: root
    password: root

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type: trace

server:
  port: 8081


app:
  uploadPath: E:/alphafiles/