spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://192.168.0.7:3306/getsoaked?useSSL=false
    username: root
    password: root

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

server:
  port: 8081