spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.0.13:3306/getsoaked?useSSL=false
#    url: jdbc:mysql://localhost:3306/getsoaked?useSSL=false
    username: root
    password: root

server:
  port: 8081

app:
  uploadPath: E:/alphafiles/

management:
  endpoints:
    web:
      base-path: /api/actuator

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type: trace
